/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 12-nov-2011, 13:28:28
 */
package com.anjesproductions.dungeons;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;

/**
 * 
 * @author Jesus
 */
@SuppressWarnings("serial")
public class Menu extends JFrame {

	/**
	 * Creates new form Menu
	 * 
	 * @param startingPoint
	 */
	public Menu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jButton1 = new JButton();
		jButton2 = new JButton();
		jLabel1 = new JLabel();
		
		this.setTitle("OH!Dungeons");
		this.setSize(640, 480);
		this.setResizable(false);
		this.setVisible(true);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);
		
		

		jButton1.setText("Load");

		jButton2.setText("Save");
		
		jButton1.setBounds(535, 384, 89, 23);
		getContentPane().add(jButton1);
		
		jButton2.setBounds(535, 418, 89, 23);
		getContentPane().add(jButton2);
		
		
		jLabel1.setFont(new Font("Lucida Console", Font.BOLD, 1));
		jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
		jLabel1.setText("Press load to start.");
		jLabel1.setVerticalAlignment(SwingConstants.TOP);
		jLabel1.setBounds(10, 11, 400, 400);
		jLabel1.setBorder(BorderFactory.createEtchedBorder());
		getContentPane().add(jLabel1);
		
		
		
		
	}

	// Variables declaration - do not modify
	private JButton jButton1;
	private JButton jButton2;
	public JLabel jLabel1;
}
